<?php

declare(strict_types=1);

/**
 * Seo_Robots
 *
 * Builds robots.txt (spec/02, "Sitemap and robots.txt").
 *
 * A Disallow is not a lock: it asks a crawler not to index a path, and the
 * paths below are private for other reasons (the admin login, the members
 * password, the CalDAV token). robots.txt only keeps them out of the index,
 * the password and the session are the actual protection. The one thing this
 * file does protect is the CalDAV subscription token in the path, which a
 * crawler would otherwise be free to walk into and index.
 *
 * The Sitemap: line is generated from the configured hostname instead of being
 * a committed string, for the same reason the reset mail uses
 * Http_Base_Url: a hostname that lives in one place cannot drift away from the
 * site it describes.
 *
 * @author Roan Buysse <roan@tigron.be>
 */

class Seo_Robots {
	/**
	 * Build the robots.txt document
	 *
	 * @access public
	 * @return string $robots_txt
	 */
	public static function get_txt(): string {
		$lines = [];
		$lines[] = '# GS Redan — ' . Http_Base_Url::get();
		$lines[] = '# Generated by the application; edit lib/component/Seo/Robots.php.';
		$lines[] = '';

		$lines[] = 'User-agent: *';
		$lines[] = 'Allow: /';

		foreach (self::PRIVATE_PATHS as $path) {
			$lines[] = 'Disallow: ' . $path;
		}

		// /login and /members are also routable with a language prefix
		// (/fr/login, /fr/members, ...). A robots.txt line matches a path
		// prefix, so "Disallow: /login" does not cover "/fr/login" — without
		// the wildcard a crawler reaches every translated login and members
		// URL while the untranslated one is blocked.
		foreach (self::LANGUAGE_PREFIXED_PRIVATE_PATHS as $path) {
			$lines[] = 'Disallow: ' . $path;
			$lines[] = 'Disallow: /*' . $path;
		}

		foreach (self::BLOCKED_CRAWLERS as $crawler) {
			$lines[] = '';
			$lines[] = 'User-agent: ' . $crawler;
			$lines[] = 'Disallow: /';
		}

		$lines[] = '';
		$lines[] = 'Sitemap: ' . Http_Base_Url::get() . '/sitemap.xml';

		return implode("\n", $lines) . "\n";
	}

	/**
	 * Paths that exist without a language prefix only
	 *
	 * /admin and the CalDAV endpoints are deliberately unprefixed
	 * (app/front/config/routes.php), /picture is dispatched by file id.
	 *
	 * @var array $private_paths
	 */
	const PRIVATE_PATHS = [
		'/admin',
		'/caldav',
		'/caldav-edit',
		'/picture',
	];

	/**
	 * Paths that are also routable as /{language}{path}
	 *
	 * @var array $language_prefixed_private_paths
	 */
	const LANGUAGE_PREFIXED_PRIVATE_PATHS = [
		'/login',
		'/members',
	];

	/**
	 * User-agents to keep out of the site entirely
	 *
	 * Empty by default, which allows every crawler: the public page is meant
	 * to be found, and the club has no reason to be invisible. Filling this in
	 * emits one "User-agent: x / Disallow: /" group per entry.
	 *
	 * Worth knowing before filling it in: a Disallow does not stop a bot from
	 * *reading* the page — it decides whether the content may be used for
	 * training and whether the URL may be shown in an answer. Blocking the
	 * training crawlers (GPTBot, ClaudeBot, CCBot, Google-Extended, ...) and
	 * leaving the search engines and the on-demand fetchers
	 * (ClaudeBot, PerplexityBot, Googlebot) alone is a deliberate trade-off,
	 * not a free win: assistants lose the ability to cite the club's page.
	 * That is the club's call, not a technical one.
	 *
	 * @var array $blocked_crawlers
	 */
	const BLOCKED_CRAWLERS = [];
}
